name: Feature or enhancement
description: Submit a proposal for a new CPython feature or enhancement
labels: ["type-feature"]
body:
  - type: markdown
    attributes:
      value: |
        # Proposing a feature to CPython?

        You'll need to demonstrate widespread support for your idea among the community.

        Major feature proposals should generally be discussed on [Discourse](https://discuss.python.org/c/ideas/6) before opening a GitHub issue. Wait until it's clear that most people support your idea before filling in this form.
  - type: checkboxes
    attributes:
      label: Has this already been discussed elsewhere?        
      options:
        - label: I have already discussed this feature proposal on Discourse
        - label: This is a minor feature, which does not need previous discussion elsewhere
  - type: textarea
    attributes:
      label: "Links to previous discussion of this feature:"
    validations:
      required: false
  - type: input
    attributes:
      label: "Summary of proposal:"
      description: A one-line summary of your proposal.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Pitch:"
      description: >
        Explain why this feature or enhancement should be implemented and how it would be used.
        Add examples, if applicable.
        Put any code blocks inside triple backticks.
      value: |
        ```python
        # Add a code block here, if required
        ```
    validations:
      required: true
